### ISSUE TITLE
okhttp can not resolved error

### ISSUE THREAD

**Issue by aykanferhat** [debugrammer/graylog-sdk-spring-boot#3]
Search:syncSearch Line:363 
RequestBody jsonBody = RequestBody.create(requestJson, CONTENT_TYPE_JSON);
Method wait first parameter content type, second parameter requestJson. 
I added okhttp dependency
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.0</version>
        </dependency>
can now resolve

**Comment by debugrammer** [comment]
Yes, `RequestBody.create(String content, MediaType contentType)` is new from OkHttp 4.x.
The old one `RequestBody.create(MediaType contentType, String content)` was deprecated.
So if your project dependencies already have OkHttp version under 4, you should manually add 4.x to prevent error.

**Comment by debugrammer** [comment]
I added troubleshooting section in the readme.
