### ISSUE TITLE
Invalid credentials in Authorization header

### ISSUE THREAD

**Issue by artemrogov** [debugrammer/graylog-sdk-spring-boot#4]
Problem: Invalid credentials in Authorization header

When sending a request to the gray log, an access error appears, although I registered the user in the gray log and generated an access token, but there is no access to the api by the token. What could be wrong?

**Comment by debugrammer** [comment]
Did you grant appropriate permissions for the user, such as Roles (e.g. Reader, ...) and Shared Entities (e.g. streams to allow, ...)?
BTW, can you provide me more background explanation with error information with your Graylog permission settings?

**Comment by debugrammer** [comment]
@artemrogov Did you solve your problem? Are you okay with closing this issue?
